src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    
]

src/my_proj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
from . import views
from profiles.views import radial_chart
from profiles.views import user_data


urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^d3data/$', profiles.views.radial_chart, name='radial_chart'),
    url(r'^userdata/$', profiles.views.user_data, name='radial_chart'),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),

        name='show'),
    url(r'^d3data/$', views.radial_chart, name='radial_chart'),
	url(r'^userdata/$', views.user_data, name='userdata'),
]

src/templates/_brandname.html
My_Proj

src/templates/_navbar.html
{% load staticfiles %}

<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}"><Strong>HOME</a></Strong><span><img src="{% static 'muapt_microsite_files/clk.png' %}" alt=""></span></li> 
<li><a href="http://www.portal.mu-sigma.com/muapt/muapt-sections.html"><Strong>muApt SECTIONS</Strong></a><span><img src="{% static 'muapt_microsite_files/clk.png' %}" alt=""></span></li> 
<li><a href="http://www.portal.mu-sigma.com/muapt/register.html"><Strong>SAMPLE QUESTIONS</Strong></a><span><img src="{% static 'muapt_microsite_files/clk.png' %}" alt=""></span></li> 
<li><a href="http://www.portal.mu-sigma.com/muapt/faq.html"><Strong>FAQs</Strong></a></li>

src/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>{% include "_brandname.html" %}</h1>
        <p class="lead">An Awesome Tagline Goes Here</p>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Meet The Team</h2>
        <p class="lead">The Wonderful People Behind the Site</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/9/" alt="profile pic"></div>
        <p class="heavy text-center">Cassidy Coder</p>
        <h2>Front-end developer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/2/" alt="profile pic"></div>
        <p class="heavy text-center">James King</p>
        <h2>CEO</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/1/" alt="profile pic"></div>
        <p class="heavy text-center">Kate Lamport</p>
        <h2>Front-end designer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
    </div>
    </div>
  </div>
</div>

<div id="sec3">
  <div class="container">
    <div class="row">
      <div id="map-outer" class="col-md-12">
        <div id="address" class="col-md-4">
          <h2>Our Location</h2>
          <address>
            <strong>Edge Solutions Ltd.</strong><br>
            Taj Mahal<br>
            Agra<br>
            Uttar Pradesh<br>
            India - 282001<br>
            <abbr>P:</abbr> +91 0562 222 6431
          </address>
        </div>
        <div id="map-container" class="col-md-8"></div>
      </div>
    </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(27.176141, 78.042370);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">
    

    <title>muApt - Mu Sigma Aptitude and Personality Test</title>

    <!-- Bootstrap core CSS -->
	<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/style.css' %}" rel="stylesheet" >
    <link href="{% static 'site/css/dashboard.css' %}" rel="stylesheet" >
    <link href="{% static 'site/css/login.css' %}" rel="stylesheet" >
    <link href="{% static 'site/css/normalize.css' %}" rel="stylesheet" >
<!--	<link href="{% static 'site/css/print.css' %}" rel="stylesheet" media="print" > -->
	<link href="{% static 'site/css/user-profile.css' %}" rel="stylesheet" >



    {% endblock styles %}

	<!---- start-smoth-scrolling---->
	<script src="{% static 'site/js/d3.min.js' %}"></script>
	<script src="{% static 'site/js/jquery-1.11.0.min.js' %}"></script>
	<script src="{% static 'site/js/html2canvas.js' %}"></script>
	<script src="{% static 'site/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'site/js/print-profile.js' %}"></script>
 
	<script type="text/javascript">
				jQuery(document).ready(function($) {
					$(".scroll").click(function(event){		
						event.preventDefault();
						$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
					});
				});
	</script>

    
	
	<!--start-smoth-scrolling-->
  <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}
    
  </head>


  <body>

    {% block navbar %}
    <div class="banner" id="home" role="navigation">
			<div class="header">
    
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static 'site/img/logo3.png' %}" alt="" width="160" height="40">
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>



          <ul class="nav navbar-nav navbar-right" style="padding-right:5%">
            {% block navbar-right %}
              {% if user.is_authenticated %}

               <li><a style="color:#fff; padding-left:25px; padding-right:25px;" href="{% url 'profiles:show_self'%}"><strong>{{ user.get_full_name|truncatechars:20 }}</strong></a></li>

		
    <li><a href="{% url 'accounts:logout' %}" ><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
              {% endif %}
            {% endblock %}
          </ul>
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}


    
    {% block container %}
    {% endblock container %}

   {% block footer %}
   {% endblock footer %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block scripts %}
    <script src="{% static 'site/js/userdata.js' %}"></script>
    {% endblock scripts %}
  </body>
</html>

src/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title %}{{ block.super }}Home{% endblock %}
{% block navbar-left %}
{% include "_navbar.html" with active_link="home" %}
{% endblock %}
{% block navbar-right %}
{% if not user.is_authenticated %}
<li style="color:#fff; padding-left:25px; padding-right:25px;"><I>Check your muAPT score</I></li>

<li><a href="{% url 'accounts:login' %}" ><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
{% else %}
{{ block.super }}
{% endif %}
{% endblock %}
{% block container %}

<div class="banner-main">

<div class="banner-top">
<h1 style="color:#666"> ARE YOU READY FOR <br>A NEW COMPETITIVE BENCHMARK?</h1>
</div>
<span></span>
<div class="banner-bottom">
<div class="banner-slide" style="margin-top:60px">
<div id="top" class="callbacks_container">
<img src="{% static 'muapt_microsite_files/slide-1.png' %}" alt="">
</div>
<div class="clearfix"> </div>
</div>
</div>
</div>
</div>	
<!-- script-for-menu -->
<!--End-slider-script-->		
<!--end-banner-->
<!--start-idea-->
<div style="padding-top:10px;  ">
   <div class="container">
      <div class="idea-main">
         <div class="idea-top" style="background-color:#eee; ">
            <div class="col-md-5 idea-left id-left" style="float:left;  color:#FFF; width:350px; height:240px;margin-right:45px; padding-left:20px;">
               <div class="wistia_video_foam_dummy" data-source-container-id="" style="border: 0px; display: block; height: 0px; margin: 0px; padding: 0px; position: static; visibility: hidden; width: auto;"></div>
               <iframe src="{% static 'muapt_microsite_files/lybts4fohu.html' %}" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen="allowfullscreen" mozallowfullscreen="mozallowfullscreen" webkitallowfullscreen="webkitallowfullscreen" oallowfullscreen="oallowfullscreen" msallowfullscreen="msallowfullscreen" width="315" height="177" style="width: 315px; height: 177px;"></iframe><script src="{% static 'muapt_microsite_files/E-v1.js' %}"></script>
            </div>
            <div class="col-md-5 idea-left id-left"></div>
            <div class="col-md-7 idea-right id-right">
               <h3>The WHY and WHAT of muApt</h3>
               <p>At Mu Sigma we’ve always had a unique recruitment process. We believe innovation is the key to growth and success. This thought process led us to create an innovative nationwide evaluation called <strong>muApt - Mu Sigma Aptitude and Personality Test</strong>. </p>
            </div>
            <div class="clearfix"></div>
         </div>
         <div class="idea-top" style="padding:25px; margin-top:0px; ">
            <div class="col-md-7 idea-right id-one-left">
               <p style="padding-top:0px; margin-top:0px;"><strong>muApt is not just about assessing your academic ability or aptitude but also evaluating the whole personality. </strong></p>
               <p>We believe that the mix of left and right brain is needed to become a successful Decision Scientist and muApt will help us find that out about you.</p>
               <p>                   
                  So, take your first step to join the world’s Decision Sciences leader, by taking on India’s newest challenge.  Discover the new competitive benchmark! 
               </p>
               <p>
                  muApt is going to put your analytical, logical and creative sides to the test. Are you ready for the brain jog, or shall we say, the brain sprint?
               </p>
               <span class="i-btn" style="float:left">
               <a onclick="_gaq.push([&#39;_trackEvent&#39;, &#39;hyperlink&#39;, &#39;click&#39;, &#39;muApt-test-section&#39;]);" href="http://www.portal.mu-sigma.com/muapt/muapt-sections.html">TEST SECTIONS</a>
               </span>
               <span class="i-btn" style="float:left">
               <a onclick="_gaq.push([&#39;_trackEvent&#39;, &#39;hyperlink&#39;, &#39;click&#39;, &#39;muApt-sample-Q-1stp&#39;]);" href="http://www.portal.mu-sigma.com/muapt/register.html">TRY THE SAMPLE QUESTIONS</a>
               </span>
               <div class="clearfix"></div>
            </div>
            <div class="col-md-5 idea-left id-one-right" style=" margin-left:0px; padding-left:0px; padding-top:20px;">
               <img src="{% static 'muapt_microsite_files/muapt1.png' %}" alt="" width="500" height="345">
            </div>
         </div>
      </div>
   </div>
</div>
<!--end-idea-->
<!--Slider-Starts-Here-->
  
       {% endblock container %}
   

    <!-- Site footer -->
    {% block footer %}
      <!--start-footer-->
    
<div class="footer">
      <div class="footer-main" style="height:8%">
            <div class="contact" style="background-color:#800000; border-top:0px">
            <div class="col-md-8 contact-left">
               <p></p><h3 style="color:#FFFFFF">We promise you it will be exciting and fun!</h3><p></p>
            </div>
            <div class="col-md-4 contact-right">
               <h3 style="color:#FFF">CONTACT</h3>
               <p style="color:#FFF; font-size:14px">For any queries please write to </p>
               <p style="color:#FFF; font-size:14px"><a style="color:#FFF; font-size:14px" href="http://www.portal.mu-sigma.com/muapt/muApt@mu-sigma.com">muApt@mu-sigma.com</a></p>
            </div>
            <div class="clearfix"></div>
         </div>
      <div class="footer-bottom">
         <div class="col-md-4 footer-left">
            <ul>
               <li><a href="https://www.facebook.com/musigmaofficial" target="_new"><span class="fb"> </span></a></li>
               <li><a href="https://twitter.com/MuSigmaInc" target="_new"><span class="twit"> </span></a></li>
               <li><a href="http://www.portal.mu-sigma.com/muapt/index.html#"><span class="sky"> </span></a></li>
            </ul>
         </div>
         <div class="col-md-4 footer-middle">
            <p><a href="http://www.mu-sigma.com/">www.mu-sigma.com</a></p>
         </div>
         <div class="col-md-4 footer-right">
            <p><a href="http://www.portal.mu-sigma.com/muapt/index.html#home" class="scroll">TO THE TOP</a></p>
         </div>
   </div>
</div>
</div>
   <!--end-footer-->

    {% endblock footer %}

src/templates/muapt_microsite.html
<!DOCTYPE html>
<!-- saved from url=(0047)http://www.portal.mu-sigma.com/muapt/index.html -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>muApt - Mu Sigma Aptitude and Personality Test</title>
<meta name="viewport" content="width=device-width, initial-scale=1">



<script type="text/javascript" async="" src="http://stats.g.doubleclick.net/dc.js"></script><script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="./muapt_microsite_files/bootstrap.css" rel="stylesheet" type="text/css">
<link href="./muapt_microsite_files/style.css" rel="stylesheet" type="text/css">
<script src="./muapt_microsite_files/jquery-1.11.0.min.js"></script>
<link href="./muapt_microsite_files/css" rel="stylesheet" type="text/css">
<link href="./muapt_microsite_files/css(1)" rel="stylesheet" type="text/css">
<link href="./muapt_microsite_files/css(2)" rel="stylesheet" type="text/css">
<!---- start-smoth-scrolling---->
<script type="text/javascript" src="./muapt_microsite_files/move-top.js"></script>
<script type="text/javascript" src="./muapt_microsite_files/easing.js"></script>
<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){		
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
				});
			});
		</script>

	
<!--start-smoth-scrolling-->


<!-- Google Analytics -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-22264337-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>


<!-- Google Analytics -->



</head>
<body>
<!--start-banner-->
	<div class="banner" id="home">
			<div class="header">
			<div class="logo">
				<a href="http://www.portal.mu-sigma.com/muapt/index.html"><img src="./muapt_microsite_files/logo3.png" alt="" width="239" height="60"></a>
			</div>
			<div class="navigation">
				 <span class="menu"></span> 
					<ul class="navig">
						<li><a href="http://www.portal.mu-sigma.com/muapt/index.html">HOME</a></li><span><img src="./muapt_microsite_files/clk.png" alt=""></span>
						<li><a href="http://www.portal.mu-sigma.com/muapt/muapt-sections.html">muApt SECTIONS</a></li><span><img src="./muapt_microsite_files/clk.png" alt=""></span>
						<li><a href="http://www.portal.mu-sigma.com/muapt/register.html">SAMPLE QUESTIONS</a></li><!--<span><img src="images/clk.png" alt="" /></span>
						<li><a href="timelines.html">Timelines</a></li>--><span><img src="./muapt_microsite_files/clk.png" alt=""></span>
			  <li><a href="http://www.portal.mu-sigma.com/muapt/faq.html">FAQs</a></li>
					</ul>
			</div>
				<div class="clearfix"></div>
			</div>
			<div class="banner-main">
				<div class="container">	
					<div class="banner-top">
						<h1 style="color:#666"> ARE YOU READY FOR <br>A NEW COMPETITIVE BENCHMARK?</h1>
						<!--<div class="banner-top-btm">
							<div class="col-md-6 bnr-left">
								<img src="images/icn-1.png" alt="" />
							</div>
							<div class="col-md-6 bnr-right">
								<img src="images/icn-2.png" alt="" />
							</div>
							<div class="clearfix"></div>
						</div>-->
					</div>
					<div class="banner-bottom">
						<div class="banner-slide" style="margin-top:60px">
						<div id="top" class="callbacks_container">
			      			<ul class="rslides callbacks callbacks1" id="slider4">
				        	<li id="callbacks1_s0" class="callbacks1_on" style="display: block; float: left; position: relative; opacity: 1; z-index: 2; transition: opacity 500ms ease-in-out;">
                            
								<img src="./muapt_microsite_files/slide-1.png" alt="">
							</li>
							<!--<li>
								<img src="images/slide-1.png" alt="" />
							</li>
							<li>
								<img src="images/slide-1.png" alt="" />
							</li>-->
			      	</ul>
			    </div>
			  <div class="clearfix"> </div>
			  </div>
				</div>
				</div>
			</div>
		</div>	
	<!-- script-for-menu -->
		 <script>
				$("span.menu").click(function(){
					$(" ul.navig").slideToggle("slow" , function(){
					});
				});
		 </script>
		 <!-- script-for-menu -->
		  <!--Slider-Starts-Here-->
				<script src="./muapt_microsite_files/responsiveslides.min.js"></script>
			 <script>
			    // You can also use "$(window).load(function() {"
			    $(function () {
			      // Slideshow 4
			      $("#slider4").responsiveSlides({
			        auto: true,
			        pager: true,
			        nav: false,
			        speed: 500,
			        namespace: "callbacks",
			        before: function () {
			          $('.events').append("<li>before event fired.</li>");
			        },
			        after: function () {
			          $('.events').append("<li>after event fired.</li>");
			        }
			      });
			
			    });
			  </script>
			<!--End-slider-script-->		
	<!--end-banner-->
	<!--start-idea-->
	<div style="padding-top:10px;  ">
		<div class="container">
			<div class="idea-main">
				<div class="idea-top" style="background-color:#eee; ">
                <div class="col-md-5 idea-left id-left" style="float:left;  color:#FFF; width:350px; height:240px;margin-right:45px; padding-left:20px;">
<div class="wistia_video_foam_dummy" data-source-container-id="" style="border: 0px; display: block; height: 0px; margin: 0px; padding: 0px; position: static; visibility: hidden; width: auto;"></div><iframe src="./muapt_microsite_files/lybts4fohu.html" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen="allowfullscreen" mozallowfullscreen="mozallowfullscreen" webkitallowfullscreen="webkitallowfullscreen" oallowfullscreen="oallowfullscreen" msallowfullscreen="msallowfullscreen" width="315" height="177" style="width: 315px; height: 177px;"></iframe><script src="./muapt_microsite_files/E-v1.js"></script>

                
                
                
                </div>
					<div class="col-md-5 idea-left id-left"></div>
					<div class="col-md-7 idea-right id-right">
						<h3>The WHY and WHAT of muApt</h3>
						<p>At Mu Sigma we’ve always had a unique recruitment process. We believe innovation is the key to growth and success. This thought process led us to create an innovative nationwide evaluation called <strong>muApt - Mu Sigma Aptitude and Personality Test</strong>. </p>
						<!--<div class="i-btn">
							<a href="services.html">LEARN MORE</a>
						</div>-->
					</div>
					<div class="clearfix"></div>
				</div>
                
                
                
                
                
                
				<div class="idea-top" style="padding:25px; margin-top:0px; ">
					<div class="col-md-7 idea-right id-one-left">
						<!--<h3>WHY muApt?</h3>-->
						<p style="padding-top:0px; margin-top:0px;"><strong>muApt is not just about assessing your academic ability or aptitude but also evaluating the whole personality. </strong></p><p>We believe that the mix of left and right brain is needed to become a successful Decision Scientist and muApt will help us find that out about you.</p>
                        
                        
     <p>                   
So, take your first step to join the world’s Decision Sciences leader, by taking on India’s newest challenge.  Discover the new competitive benchmark! </p>
<p>
muApt is going to put your analytical, logical and creative sides to the test. Are you ready for the brain jog, or shall we say, the brain sprint?
</p>
                        
					  <span class="i-btn" style="float:left">
							<a onclick="_gaq.push([&#39;_trackEvent&#39;, &#39;hyperlink&#39;, &#39;click&#39;, &#39;muApt-test-section&#39;]);" href="http://www.portal.mu-sigma.com/muapt/muapt-sections.html">TEST SECTIONS</a>
					  </span>
                         <span class="i-btn" style="float:left">
							<a onclick="_gaq.push([&#39;_trackEvent&#39;, &#39;hyperlink&#39;, &#39;click&#39;, &#39;muApt-sample-Q-1stp&#39;]);" href="http://www.portal.mu-sigma.com/muapt/register.html">TRY THE SAMPLE QUESTIONS</a>
						</span>
                       <div class="clearfix"></div>
</div>
                    
                    
					<div class="col-md-5 idea-left id-one-right" style=" margin-left:0px; padding-left:0px; padding-top:20px;">
						<img src="./muapt_microsite_files/muapt1.png" alt="" width="500" height="345">
                        
					</div>
                    
               </div>
				</div>
		</div>
	</div>
	<!--end-idea-->
	<!--start-number--><!--end-number-->
	<!--start-partner--><!--end-partner-->
	<!--Slider-Starts-Here-->
				<script src="./muapt_microsite_files/responsiveslides.min.js"></script>
			 <script>
			    // You can also use "$(window).load(function() {"
			    $(function () {
			      // Slideshow 4
			      $("#slider5").responsiveSlides({
			        auto: true,
			        pager: false,
			        nav: true,
			        speed: 500,
			        namespace: "callbacks",
			        before: function () {
			          $('.events').append("<li>before event fired.</li>");
			        },
			        after: function () {
			          $('.events').append("<li>after event fired.</li>");
			        }
			      });
			
			    });
			  </script>
			<!--End-slider-script-->
	<!--start-project--><!--end-project-->
	<link rel="stylesheet" href="./muapt_microsite_files/swipebox.css">
	<script src="./muapt_microsite_files/jquery.swipebox.min.js"></script> 
	    <script type="text/javascript">
			jQuery(function($) {
				$(".swipebox").swipebox();
			});
		</script>
	<!-- Portfolio Ends Here -->
	<script type="text/javascript" src="./muapt_microsite_files/jquery.mixitup.min.js"></script>
<script type="text/javascript">
$(function () {
	
	var filterList = {
	
		init: function () {
		
			// MixItUp plugin
		// http://mixitup.io
		$('#portfoliolist').mixitup({
			targetSelector: '.portfolio',
			filterSelector: '.filter',
			effects: ['fade'],
			easing: 'snap',
			// call the hover effect
			onMixEnd: filterList.hoverEffect()
		});				
	
	},
	
	hoverEffect: function () {
	
		// Simple parallax effect
		$('#portfoliolist .portfolio').hover(
			function () {
				$(this).find('.label').stop().animate({bottom: 0}, 200, 'easeOutQuad');
				$(this).find('img').stop().animate({top: -30}, 500, 'easeOutQuad');				
			},
			function () {
				$(this).find('.label').stop().animate({bottom: -40}, 200, 'easeInQuad');
				$(this).find('img').stop().animate({top: 0}, 300, 'easeOutQuad');								
			}		
		);				
	
	}

};

// Run the show!
	filterList.init();
	
});	
</script>
	<!--start-footer-->
    
<div class="footer">
		<div class="container">
			<div class="footer-main">
            <div class="contact" style="background-color:#800000; padding-left:25px; padding-right:25px;">
					<div class="col-md-8 contact-left">
						
						<p></p><h3 style="color:#FFFFFF">We promise you it will be exciting and fun!</h3><p></p>
					</div>
					<div class="col-md-4 contact-right">
						<h3 style="color:#FFF">CONTACT</h3>
						<p style="color:#FFF; font-size:14px">For any queries please write to </p>
						<p style="color:#FFF; font-size:14px"><a style="color:#FFF; font-size:14px" href="http://www.portal.mu-sigma.com/muapt/muApt@mu-sigma.com">muApt@mu-sigma.com</a></p>
					</div>
					<div class="clearfix"></div>
			  </div>
			  <div class="footer-bottom">
				  <div class="col-md-4 footer-left">
						<ul>
							<li><a href="https://www.facebook.com/musigmaofficial" target="_new"><span class="fb"> </span></a></li>
							<li><a href="https://twitter.com/MuSigmaInc" target="_new"><span class="twit"> </span></a></li>
							<li><a href="http://www.portal.mu-sigma.com/muapt/index.html#"><span class="sky"> </span></a></li>
						</ul>
				</div>
					<div class="col-md-4 footer-middle">
						<p><a href="http://www.mu-sigma.com/">www.mu-sigma.com</a></p>
					</div>
					<div class="col-md-4 footer-right">
						<p><a href="http://www.portal.mu-sigma.com/muapt/index.html#home" class="scroll">TO THE TOP</a></p>
					</div>
					<div class="clearfix"></div>
			  </div>
		  </div>
	  </div>
	</div>
	<!--end-footer-->

</body></html>